TRAIVLER/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import main
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/',include('django_summernote.urls')),
    path('user/', include('user.urls')),
    path('', main),
    path('notice/',include('notice.urls')),
    path('ai/',include('ai.urls')),
    path('review/',include('review.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ai/urls.py
from django.urls import path
from . import views
app_name = 'ai'
urlpatterns = [
   path('result',views.result, name='result'),
   path('info',views.info, name = 'info'),
   path('db_upload',views.db_upload,name = 'db_upload'),
   
]

notice/urls.py
from django.urls import path
from. import views
app_name = 'notice'
urlpatterns = [
   path('list',views.notice_list, name='notice_list'),
   path('write',views.notice_write,name = "notice_write"),
   path('<int:pk>/', views.notice_detail, name='notice_detail'),
   path('<int:pk>/modify/', views.notice_modify, name='notice_modify'),
   path('<int:pk>/delete/', views.notice_delete, name='notice_delete'),
]

review/urls.py
from django.urls import path
from . import views
app_name = 'review'
urlpatterns = [
   path('list',views.review_list, name='review_list'),
   path('write',views.review_write,name = "review_write"),
   path('<int:pk>/', views.review_detail, name='review_detail'),
   path('<int:pk>/modify/', views.review_modify, name='review_modify'),
   path('<int:pk>/delete/', views.review_delete, name='review_delete'),
]

user/urls.py
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [    
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path('main/', views.main, name='main'),
    path("login/", views.my_login, name="login"),
    path('logout/',views.log_out, name = 'logout'),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path('mypage/',views.mypage,name = 'mypage'),
    path('traivler',views.traivler,name = 'traivler'),
    
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid 

from django.conf import settings  
from django.db import models
from django.core.mail import send_mail 
from django.utils.html import strip_tags 
from django.template.loader import render_to_string

class User(AbstractUser):
    
    username = models.CharField(max_length=20, verbose_name="아이디", unique=True,primary_key = True)
    email = models.EmailField(max_length = 30,verbose_name = '이메일',unique = True)
    password = models.CharField(max_length = 30,verbose_name= '비밀번호')
    name = models.CharField(max_length=30,verbose_name='이름')
    phone = models.CharField(max_length = 20, verbose_name= '연락처')
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=120, default="", blank=True)
    
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.username
    def verify_email(self): 
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20] 
            self.email_secret = secret  
            html_message = render_to_string(
                "verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify Traivler Account",  
                strip_tags(html_message),  
                settings.EMAIL_FROM,  
                [self.email],  
                fail_silently=False, 
                html_message=html_message,  
            )
            self.save() 
        return

user/forms.py
from django import forms
from . import models
class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = (
            "username",
            "name",
            "email",
            "phone",
        )
    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")
    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password
   
    def save(self, *args, **kwargs): 
        user = super().save(commit=False)
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        
        user.username = username
        user.email = email
        user.set_password(password) 
        user.save() 

user/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect,reverse
# from .models import User
from .models import User
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from . import forms,models
from django.contrib.auth.hashers import check_password
from review.models import Review
def main(request):
    return render(request,'main.html')
def my_login(request):
    if request.method == "GET":
        id = request.GET.get("username", None)
        password = request.GET.get("password", None)

        res = {}

        if not id:
            res['error'] = '아이디를 입력해주세요.'
        elif not password:
            res['error'] = '비밀번호를 입력해주세요.'
        else:
            try:
                user = User.objects.get(username=id)
                email_verified = user.email_verified
                if email_verified ==0:
                    res['error'] = '발송된 이메일로 계정을 인증해주세요'
                else:
                    if check_password(password, user.password):
                        authenticated_user = authenticate(request, username=id, password=password)
                    if authenticated_user is not None:
                        request.session['login_id'] = id
                        login(request, user)
                        return redirect('/')
                    else:
                        res['error'] = '비밀번호가 틀렸습니다.'
            except:
                res['error'] = '이메일이 존재하지 않습니다.'
        return render(request, "login.html", res)

    elif request.method == "POST":
        id = request.POST.get("username", None)
        password = request.POST.get("password", None)

        res = {}

        if not id:
            res['error'] = '아이디를 입력해주세요.'
        elif not password:
            res['error'] = '비밀번호를 입력해주세요.'
        else:
            try:
                user = User.objects.get(username=id)
                email_verified = user.email_verified
                if email_verified ==0:
                    res['error'] = '발송된 이메일로 계정을 인증해주세요'
                else:
                    if check_password(password, user.password):
                        authenticated_user = authenticate(request, username=id, password=password)
                    if authenticated_user is not None:
                        request.session['login_id'] = id
                        login(request, user)
                        return redirect('/')
                    else:
                        res['error'] = '비밀번호가 틀렸습니다.'
            except:
                res['error'] = '이메일이 존재하지 않습니다.'
        return render(request, "login.html", res)
    
def log_out(request):
    logout(request) 
    return redirect('/')

class SignUpView(FormView):
    template_name = "signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("user:traivler")
    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        user.verify_email() 
        return super().form_valid(form)
def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key) 
        user.is_active = True
        user.email_verified = True 
        user.email_secret = ""
        user.save()
    except models.User.DoesNotExist:
        
        pass
    return redirect(reverse("user:traivler"))


def mypage(request):
    login_session = request.session.get('login_id','')
    text = Review.objects.filter(writer = login_session)
    
    context = {'reviews':text}
    return render(request, "mypage.html",context)

def traivler(request):
    return render(request,"traivler.html")

user/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Traivler</title>
<link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-barun-gothic.css" rel="stylesheet">

<style>
    *{
        font-family: 'NanumBarunGothicLight';

    }
</style>
 <nav class="navbar navbar-light bg-light fixed-top" style="background-color: #ffff; padding:0;">
  <div class="container-fluid"style="background-color: #ffff; padding: 10px">
    <a href="http://127.0.0.1:8000" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <img src="https://postfiles.pstatic.net/MjAyMjEyMjJfMzAw/MDAxNjcxNjc0MDg5NDc1.K6IZ-bbwy_YGFP20SiAL-KAu2VVXDZ-FL3k155JHcPcg.zAahbo4yJ8BJGcnizMseYN-9tnwzb_m1grJ8h3Tx_4Qg.PNG.thisjis/1051-removebg-preview.png?type=w966" alt="로고" height="50" width="200">
      </a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <style>
        .navbar-toggler{

          border:none;
        }
        .navbar-toggler:active, .navbar-toggler:focus 
        { border: none !important; box-shadow: none !important; }
      </style>
      
      <span class="navbar-toggler-icon">
        <style>
          .navbar-toggler-icon{
            color: #b0dee1;
            width:30px;
          }
         
        </style>
      </span> <!--메뉴 아이콘-->
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
              {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'user:logout' %}">{{ user.username }} (로그아웃)</a>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      MyPage
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'user:mypage' %}">마이페이지</a></li>
                      <li><a class="dropdown-item" href="#">회원정보 설정</a></li>
        
                    </ul>
                  </li>
              {% else %}
                  <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">Login</a>
                  
                  <a class="nav-link" href="{% url 'user:signup' %}">Sign up</a>
                  

            {% endif %}
        
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notice:notice_list' %}">공지사항</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'review:review_list' %}">리뷰게시판</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:traivler' %}">트레이블러란?</a>
            </li>
          
        </ul>
      </div>
    </div>
  </div>
</nav>
</head>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<body class="pt-5" >
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

</body>

</html>

user/templates/login.html
{% extends "base.html" %}
{% block content %}
    <style>
    *{
        font-family: 'NanumBarunGothicLight';

    }
     /* link - 아직 클릭하지 않은 경우 red 색상 설정 */
     a:link { color: black; text-decoration: none;}	
    /* visited - 한번 클릭하거나 전에 클릭한적 있을 경우  */
    a:visited { color: black; text-decoration: none;}	
    /* hover - 마우스를 해당 링크에 위치했을 경우 설정 */
    a:hover { color: #19bec9; text-decoration: underline;}

</style>

    <body>
        <style>
            body {

                    background-color:#f2f2f6;

                background-image:url('/static/img/main.png');
                background-repeat: no-repeat;
                background-size: cover;
                }
        </style>
<div style="padding-top: 100px">
<div class="container my-3" style="margin: 0 auto; border:none; padding:30px;width: 500px;border-radius: 10px; background-color: #ffffff;">
<h4 style="padding-left: 175px ; padding-bottom: 20px; font-family: NanumBarunGothicRegular;" >로그인</h4>

    <form method="post" action="{% url 'user:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        <div style="width: 250px; margin:0 auto;">
        <div class="mb-3">
            <input type="text" class="form-control" name="username" id="username" placeholder="아이디"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <input type="password" class="form-control" name="password" id="password" placeholder="비밀번호"
                   value="{{ form.password.value|default_if_none:'' }}">
             <div style="padding-top: 10px; padding-left: 1px;">
                    <label style = "float:left;"><input type="checkbox" id="saveBtn"> 아이디 기억하기</label>
             <div>
                 <ul>
                            {% if not user.is_authenticated %}
                            <a href="{% url 'user:signup' %}"  style="padding-left: 50px;">회원가입
                            </a>
                            

                        {% endif %}
                        </ul>
             </div>

                </div>
        </div >
            <div style="padding-left: 50px;">
        <button type="submit" class="btn text-white" style="background-color:#19bec9;width: 150px; border-radius:10px; font-family:NanumBarunGothicRegular; font-weight:bold;">로그인</button>
        </div>

    </form>
</div>
</div>
</div>

    </body>
{% endblock %}

user/templates/main.html
{% extends "mainbase.html" %}
{% block content %}



<html lang="en">

<head>

  <!-- ▼ 부트스트랩 css 사용 -->
  <link rel="stylesheet" href="../static/css/main.css" />
  <link rel="stylesheet" href="../static/css/mainmain.css" />
  <!--▲ 부트스트랩 css 사용-->


  <link rel="stylesheet" href="../static/css/ment.css" />

  <!--▼ 검색 워닝 위치조절-->
  <!--<link rel="stylesheet" href="../static/css/indekwarn.css" />-->
  <!--▲ 검색 워닝 위치조절-->

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1 " />
  <title>Document</title>
  
<style>
  div.warning 
  {position : absolute; top:140px; left: 0px; }

@media screen and (max-width:473px){
    div.warning{
        position: absolute;
        top:230px;
        left:0px;

    }

}




</style>
 <style>
        *{
        font-family: 'NanumBarunGothicLight';

    }

        .container{
            display: flex;
            flex-direction: column; /*글을 세로로 배치*/
            height: 100%;
        }
        .top-bar{
            display:flex;
            align-items: center;
            text-align: right;
            justify-content: flex-end;
            padding: 6px;

        }
        .top-bar>a{
            text-decoration: none;
            color: black;
        }
        .top-bar>#mail:hover, .top-bar>#image:hover{
            text-decoration: underline;
        }
        .top-menu{
            margin : 5px 15px;
            font-size: 15px;
        }

        .logo{
            display:flex;
            font-size: 100px;
            font-weight: 550;
            justify-content: center;
            margin-top: 24.364px;
        }

        .Search{
            padding: 20px;
        }
        .search-box-tool{
            position: relative;
            margin: 0 auto;
            padding-top: 6px;
            max-width: 584px;
        }
        .search-box{
            padding: .2em .5em;
            align-content: center;
            background-color: white;
            width: 100%;
            height: 46px;
            border: 1px solid #dfe1e5;
            border-radius: 30px;
            min-width: 360px;
            position: relative;
        }
        .search-box:hover{
            box-shadow: 0px 0px 10px gainsboro;
        }
        input:focus{
            outline: none;
        }
        search-box>#input1{
            position: absolute;
            align-content: center;
            width: 76%;
            height: 90%;
            left: 8%;
            font-size: 17px;
            border: none;
        }
        search-box>.fa-search{
            position: absolute;
            color:#70757a;
            top: 28%;
            font-size: 20px;
            left: 2%;
            z-index: 1;
        }
        keyboard, microphone{
            font-size: 12px;
            position: absolute;
            text-align: center;
            width: 65px;
            padding: 8px;
            background: #333;
            color: #fff;
        }
        .keyboard:after{
            /*
            bottom: 100%;
            width: 0;
            margin-left: -10px;
            position: absolute;
            left: 50%;
            height: 0;
            border-color: rgba(51, 51, 51, 0);
            border-bottom-color: #333;
            border-width: 10px;
            border: solid transparent;
            pointer-events: none;
            content: " ";
            */
        }
        search-box>.fa-keyboard{
            position: absolute;
            cursor: pointer; /*손모양 커서*/
            color:#70757a;
            top: 28%;
            font-size: 20px;
            right: 8%;
        }
        search-box>.fa-keyboard:hover .keyboard{
            visibility: visible;
        }
        search-box>.fa-microphone{
            position: absolute;
            cursor: pointer; /*손모양 커서*/
            color:#70757a;
            top: 28%;
            font-size: 20px;
            right: 3%;
        }

        search-click-bar{
            padding-top: 18px;
        }
        etc{
            display: flex;
            justify-content: center;
        }
        contents{
            background-color: #f8f9fa;
            color: #3c4043;
            border: 1px solid #f8f9fa;
            padding: 0 16px;
            margin: 11px 4px;
            line-height: 35px;
            height: 36px;
            border-radius: 4px;
            text-decoration: none;

        }
        contents:hover{
            border: 1px solid gainsboro;
            box-shadow: 0px 0px 5px gainsboro;
        }

        content{
            flex-grow: 1;/*빈자리 content자리로 채우기*/
        }
        service-bar{
            display: flex;
            justify-content: center;
        }
        service-bar>div>a{
            padding: 0 3px;
            text-decoration: none;
        }
        service-bar>div>a:hover{
            text-decoration: underline;
        }

        bottom-bar{
            background-color: #f2f2f2;
            align-items: flex-end;
            flex-shrink: 0; /*옆 비지 않게 채우기*/
        }
        country{
            border: 1px solid #dadce0;
            color:#70757a;
            padding: 15px 30px;
            font-size: 15px;
        }
        Bottom{
            display: flex;
            justify-content: space-evenly;
            flex-wrap: wrap;
            padding: 0 20px;
        }
        bottom-left, .bottom-right{
            display: flex;
            flex-wrap: wrap;
        }
        bottom-item{
            text-decoration: none;
            color:#70757a;
            display: block;
            padding: 15px;
            white-space: nowrap;
            font-size: 14px;
        }
        bottom-item:hover{
            text-decoration: underline;
        }


    </style>
</head>
<body class="is-preload">
<div class="container" style="padding-top: 10px" >
        <div class="top-bar">

            <a href="" class="top-menu" id="menu"><i class="fas fa-bars"></i></a>
            <a href="" style="font-size: 30px;" class="top-menu" id="profile"><i class="fab fa-github"></i></a>
        </div>

        <div class="logo" style="padding-top: 100px">
            <a class="navbar-brand"  href="http://127.0.0.1:8000/" >
        <img src="https://postfiles.pstatic.net/MjAyMjEyMjJfMzAw/MDAxNjcxNjc0MDg5NDc1.K6IZ-bbwy_YGFP20SiAL-KAu2VVXDZ-FL3k155JHcPcg.zAahbo4yJ8BJGcnizMseYN-9tnwzb_m1grJ8h3Tx_4Qg.PNG.thisjis/1051-removebg-preview.png?type=w966" alt="로고" height="100" width="410">
      </a>
        </div>
        <form id="search_bar" method="post" action="{% url 'ai:result' %}" onsubmit="return search_submit()">
            {% csrf_token %}
    
            <div class="-" >
            <div class="search-box-tool" >
            <div class="mb-3" >
                <input type="text" class="form-control" name="input_text" id="input_text"
                       value="{{ form.input_text.value|default_if_none:''}}" placeholder="부산에서 어디로 가고 싶은지 트레이블러에게 말씀해 주세요 :)" style="border-radius: 30px;font-size: 13px;padding-left: 20px;height: 40px;color:white">
            </div>
            </div>
             <div class="etc" style="padding-left: 355px">
                    <h4  class="contents" style = "font-size: 13px;">트레이블러는 사용자님의 기분과 상황에 따른 알맞은 장소를 AI로 분석해서 추천해 드리는 시스템입니다.</h4>
                </div>
            <div style="padding-left: 560px;padding-top: 30px">
                <button type = "submit" class="btn text-white" style="background-color:#19bec9;width: 150px;border-radius: 15px;" >검색</button>
            </div>
        </form>




<!-- Scripts -->
<script src="../static/js/main.js"></script>
 <!-- 검색창에 아무 검색어가 없으면 페이지 이동이 없게 -->
<script>
    function search_submit(){
        var check = document.getElementById("input_text").value
        if(check.trim()==''){
            alert("아무 말씀을 안하시면 추천이 불가능해요 :(");
            return false;
        }
        else {
            document.search_bar.submit();
        }
    };
</script>

</body>
</html>
{% endblock %}

user/templates/mainbase.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Traivler</title>
<link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-barun-gothic.css" rel="stylesheet">

<style>
    *{
        font-family: 'NanumBarunGothicLight';

    }
</style>
<nav class="navbar navbar-light bg-light fixed-top" style="background-color: transparent; padding:0;">
  <div class="container-fluid"style="background-color: transparent; padding: 10px; padding-left: 1472px;padding-top: 16px">

    
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <style>
        .navbar-toggler{

          border:none;
        }
        .navbar-toggler:active, .navbar-toggler:focus 
        { border: none !important; box-shadow: none !important; }
      </style>
      
      <span class="navbar-toggler-icon">
        <style>
          .navbar-toggler-icon{
            color: #b0dee1;
            width:30px;
          }
         
        </style>
      </span> <!--메뉴 아이콘-->
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
              {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'user:logout' %}">{{ user.username }} (로그아웃)</a>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      MyPage
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'user:mypage' %}">마이페이지</a></li>
                      <li><a class="dropdown-item" href="#">회원정보 설정</a></li>
        
                    </ul>
                  </li>
              {% else %}
                  <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">Login</a>
                  
                  <a class="nav-link" href="{% url 'user:signup' %}">Sign up</a>
                  

            {% endif %}
        
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notice:notice_list' %}">공지사항</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'review:review_list' %}">리뷰게시판</a>
          </li>
<li class="nav-item">
                <a class="nav-link" href="{% url 'user:traivler' %}">트레이블러란?</a>
            </li>
          
        </ul>
      </div>
    </div>
  </div>
</nav>
</head>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<body class="pt-5" >
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

</body>

</html>

user/templates/search.html
{% load static %}
<!doctype html>

<html lang="ko-KR">
<head>
    <link href="/static/styles/chat.css" rel="stylesheet" type="text/css">
    <meta charset="utf-8">
    <title>traivler</title>
</head>

<body>
    <style>
        body {
        background-image:url('./img/Group 89.png');
        background-repeat: no-repeat;
        background-size: cover;
        }
</style>

<head>
</head>
 
    <div class='result' style='flex:0'>
      정답 : {{result.result}}
    </div >
 
  
</body>

user/templates/signup.html
{% extends "base.html" %}
{% block content %}
<style>
    *{
        font-family: 'NanumBarunGothicLight';

    }
            body {
            background-color:#f2f2f6;

            background-image:url('/static/img/main.png');
            background-repeat: no-repeat;
            background-size: cover;
            }
</style>
    <body>
    <div style="padding-top: 100px">

<div class="container my-3" style="border: none; padding:30px;width: 500px;border-radius: 15px; background-color: #ffffff;">
<h4 style="padding-left: 170px; padding-bottom: 20px; font-family: NanumBarunGothicRegular;">회원가입</h4>
    <form method="post" action="{% url 'user:signup' %}">
        {% csrf_token %}

        <div style="width: 250px; margin:0 auto;">
        <div class="mb-3">
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}" placeholder="아이디">
        </div>
        <div class="mb-3">
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}" placeholder="비밀번호">
        </div>
            <div class="mb-3">
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}" placeholder="비밀번호 확인">
            </div>
        <div class="mb-3">
            <input type="text" class="form-control" name="name" id="name"
                   value="{{ form.name.value|default_if_none:'' }}" placeholder="이름">
        </div>

        <div class="mb-3">
            <input type="phone" class="form-control" name="phone" id="phone"
                   value="{{ form.phone.value|default_if_none:'' }}" placeholder="전화번호">
        </div>
        <div class="mb-3">
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}" placeholder="이메일 (입력한 이메일로 인증)">
        </div>
            <div style="padding-left: 50px;padding-top: 10px">
        <button type="submit" class="btn text-white" style="border-radius: 10px; background-color:#19bec9;width: 150px; font-weight:bold;">회원가입</button>
        </div>
    </form>
    </div>
</div>

    </div>
    </div>
    </div>
    </body>
{% endblock %}

user/templates/verify_email.html
<h4>Verify Email</h4>
<span>Hello, to verify your email click <a href="http://127.0.0.1:8000/user/verify/{{secret}}">here</a></span>