TRAIVLER/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import main
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/',include('django_summernote.urls')),
    path('user/', include('user.urls')),
    path('', main),
    path('notice/',include('notice.urls')),
    path('ai/',include('ai.urls')),
    path('review/',include('review.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ai/urls.py
from django.urls import path
from . import views
app_name = 'ai'
urlpatterns = [
   path('result',views.result, name='result'),
   path('info',views.info, name = 'info'),
   path('db_upload',views.db_upload,name = 'db_upload'),
   
]

notice/urls.py
from django.urls import path
from. import views
app_name = 'notice'
urlpatterns = [
   path('list',views.notice_list, name='notice_list'),
   path('write',views.notice_write,name = "notice_write"),
   path('<int:pk>/', views.notice_detail, name='notice_detail'),
   path('<int:pk>/modify/', views.notice_modify, name='notice_modify'),
   path('<int:pk>/delete/', views.notice_delete, name='notice_delete'),
]

review/urls.py
from django.urls import path
from . import views
app_name = 'review'
urlpatterns = [
   path('list',views.review_list, name='review_list'),
   path('write',views.review_write,name = "review_write"),
   path('<int:pk>/', views.review_detail, name='review_detail'),
   path('<int:pk>/modify/', views.review_modify, name='review_modify'),
   path('<int:pk>/delete/', views.review_delete, name='review_delete'),
]

user/urls.py
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [    
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path('main/', views.main, name='main'),
    path("login/", views.my_login, name="login"),
    path('logout/',views.log_out, name = 'logout'),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path('mypage/',views.mypage,name = 'mypage'),
    path('traivler',views.traivler,name = 'traivler'),
    
]

review/models.py
import os
from django.db import models
from django.conf import settings
from uuid import uuid4

# Create your models here.

class Review(models.Model):
    writer = models.ForeignKey('user.User', on_delete=models.CASCADE,verbose_name= '작성자')
    register_date = models.DateField(auto_now_add=True, verbose_name='등록시간')
    title = models.TextField(max_length=128, verbose_name='리뷰제목')
    contents = models.TextField(verbose_name = '리뷰내용')
    hits = models.PositiveBigIntegerField(verbose_name='조회수',default =0)
    top_fixed = models.BooleanField(verbose_name='상단고정',default = False)
    review_image = models.ImageField(verbose_name='리뷰이미지',blank = True,upload_to='rImg')
    place = models.ForeignKey('ai.Place', on_delete=models.CASCADE,verbose_name= '장소')
    
    
    def __str__(self):
        return self.title

review/forms.py
from django import forms
from .models import Review
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget

class ReviewWriteForm(forms.ModelForm):
    title = forms.CharField(
        label = '리뷰 제목',
        widget = forms.TextInput(
            attrs = {
                'placeholder':'게시글 제목'
            }   
        ),
        required=True,
    )
    
    contents = SummernoteTextField()
    field_order = [
        'title',
        'contents'
    ]   
    class Meta:
        model = Review
        fields = [
            'title',
            'contents',
            
        ]
        widgets = {
            'contents' : SummernoteWidget()
            
        }
        
    title.widget.attrs['size'] = 80
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title','')
        contents = cleaned_data.get('contents','')
        
        if title == '':
            self.add_error('title','글 제목을 입력하세요.')
        elif contents =='':
            self.add_error('contents','글 내용을 입력하세요.') 
        else :
            self.title=title
            self.contents = contents
            

review/views.py
from django.shortcuts import render,redirect
from .forms import ReviewWriteForm
from .models import Review
from user.models import User
from django.shortcuts import get_object_or_404
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from ai.models import Place

#Create your views here.

def review_list(request):
    review= Review.objects.all().order_by('id')
    length = len(review)
    return render(request, 'review_list.html', {"review":review,"length":length})

def review_detail(request, pk):
    review = get_object_or_404(Review, pk=pk)
    context = {
        'review': review,
    }
    response = render(request,'review_detail.html',context)
    expire_date, now = datetime.now(),datetime.now()
    expire_date+=timedelta(days = 1)
    expire_date = expire_date.replace (hour=0,minute=0,second=0,microsecond=0)
    expire_date -= now
    max_page = expire_date.total_seconds()
    
    cookie_value = request.COOKIES.get('hitboard','_')
    
    if f'_{pk}_' not in cookie_value:
        cookie_value +=f'{pk}_'
        response.set_cookie('hitboard',value = cookie_value,max_age = max_page,httponly=True)
        review.hits +=1
        review.save()
    return render(request, 'review_detail.html', context)


@login_required(login_url='/user/login/')
def review_write(request):
    login_session = request.session.get('login_id','')
    place = request.GET.get("place_info",None)
    context = {'login_session':login_session,"place":place}
    
    if request.method == "GET":
        form = ReviewWriteForm()
        context['forms'] = form
        return render(request,'review_write.html',context)

    elif request.method == "POST":
        form = ReviewWriteForm(request.POST)
        
        if form.is_valid():
            writer = User.objects.get(username = login_session)
            myplace = Place.objects.get(place_name = place)
            review = Review(
                title=form.title,
                contents = form.contents,
                writer = writer,
                place = myplace,
            )
            review.save()
            return redirect('/review/list')
        
        else:
            context['forms'] = form
            if form.errors:
                for value in  form.values():
                    context['error']=value
            return render(request,'review_write.html',context)
        

@login_required(login_url='/user/login/')
def review_modify(request,pk):
    login_session = request.session.get('login_id','')
    context = {'login_session':login_session}
    
    review = get_object_or_404(Review, pk= pk)
    context['review'] = review
    
    if review.writer.username != login_session:
        
        return redirect(f'/review/{pk}/')
    if request.method == "GET":
        form = ReviewWriteForm(instance = review)
        context['forms'] = form
        return render(request,'review_modify.html',context)

    elif request.method == "POST":
        form = ReviewWriteForm(request.POST)
        
        if form.is_valid():
            
            review.title=form.title
            review.contents = form.contents          
            
            review.save()
            return redirect('/review/list')
        
        else:
            context['forms'] = form
            if form.errors:
                for value in  form.values():
                    context['error']=value
            return render(request,'review_modify.html',context)

@login_required(login_url='/user/login/')
def review_delete(request,pk):
    login_session = request.session.get('login_id','')
    review = get_object_or_404(Review,pk=pk)
    if review.writer.username ==login_session:
        review.delete()
        return redirect('/review/list')
    else:
        return redirect(f'/review/{pk}')
    

review/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Traivler</title>
<link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-barun-gothic.css" rel="stylesheet">

<style>
    *{
        font-family: 'NanumBarunGothicLight';

    }
</style>
 <nav class="navbar navbar-light bg-light fixed-top" style="background-color: #ffff; padding:0;">
  <div class="container-fluid"style="background-color: #ffff; padding: 10px">
    <a href="http://127.0.0.1:8000" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <img src="https://postfiles.pstatic.net/MjAyMjEyMjJfMzAw/MDAxNjcxNjc0MDg5NDc1.K6IZ-bbwy_YGFP20SiAL-KAu2VVXDZ-FL3k155JHcPcg.zAahbo4yJ8BJGcnizMseYN-9tnwzb_m1grJ8h3Tx_4Qg.PNG.thisjis/1051-removebg-preview.png?type=w966" alt="로고" height="50" width="200">
      </a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <style>
        .navbar-toggler{

          border:none;
        }
        .navbar-toggler:active, .navbar-toggler:focus 
        { border: none !important; box-shadow: none !important; }
      </style>
      
      <span class="navbar-toggler-icon">
        <style>
          .navbar-toggler-icon{
            color: #b0dee1;
            width:30px;
          }
         
        </style>
      </span> <!--메뉴 아이콘-->
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
              {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'user:logout' %}">{{ user.username }} (로그아웃)</a>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      MyPage
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'user:mypage' %}">마이페이지</a></li>
                      <li><a class="dropdown-item" href="#">회원정보 설정</a></li>
        
                    </ul>
                  </li>
              {% else %}
                  <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">Login</a>
                  
                  <a class="nav-link" href="{% url 'user:signup' %}">Sign up</a>
                  

            {% endif %}
        
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notice:notice_list' %}">공지사항</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:signup' %}">리뷰게시판</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:traivler' %}">트레이블러란?</a>
            </li>
          
        </ul>
      </div>
    </div>
  </div>
</nav>
</head>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<body class="pt-5" >
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

</body>

</html>

review/templates/review_detail.html
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}
<br><br><br>
<div class="container">
    <div class="row-mt-5">
        <div class="col-12">
            <!--본문-->
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header">
                    <strong style="font-size: 18px;">{{ review.title }}</strong>&nbsp;&nbsp;<span style="font-size: 18px; color: gray;">[공지사항]</span>
                    <span style="float:right;">{{ review.register_date|date:'Y.m.d.' }}</span>
                </div>
                <div class="card-body" style="min-height: 400px; color:black;">
                    <!--작성자, 조회수-->
                    <div>
                        <span><i class="fas fa-user-edit"></i>&nbsp;작성자 : {{ review.writer }}</span>
                        <span style="float:right;">조회수 : {{ review.hits }}</span>
                    </div>
                    <hr>
                    {% if review.review_image %}

                        <img class = "image" src = "{{review.review_image.url}}"/>
                    {% endif %}
                    <!--내용-->
                    <div>
                        {{ review.contents | safe }}
                    </div>
                </div>
            </div>
            <br>
            <div class="text-right" style="margin-top:-15px;">
                {% if user.is_authenticated %}
                <button class = "button2"type="button" onclick="location.href='/review/{{review.id}}/modify'">수정</button>
                <button class = "button2"type="button" onclick="location.href='/review/{{review.id}}/delete'">삭제</button>
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/review/list'">목록으로</button>

                {% else %}
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/review/list'">목록으로</button>
                {% endif %}
            </div>
        </div>
    </div>

    
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('img').css('width', '100%');
    });

    function delete_modal() {
        location.replace('/review/{{ review.id }}/delete/');
    }
</script>

{% endblock %}

review/templates/review_modify.html
{% extends "base.html" %}
{% block content %}
    <head>
<style>
    *{
        font-family: 'NanumBarunGothicLight';

    }
            body {
            background-image:url('/static/img/main.png');
            background-repeat: no-repeat;
            background-size: cover;
            background-color: #f2f2f6;
            }

</style>
        </head>
    <div>
    <body >
<div style="padding-top: 50px;padding-left: 205px">
<div class= "container my-3"  style="background-color:#ffffff; border-radius: 20px;
  width: 1000px;
  height: 700px;
  transform: translate(0%, 5%);
  margin: 5%; /*위 오 아 왼*/
">
<h4 style="padding-top: 20px;text-align: center" >리뷰 수정</h4>
<hr>

<div style="padding-top: 25px;padding-left: 140px; clear: left">
<form action="" method = 'POST' >
    {% csrf_token %}
    {%for form in forms%}
    <div >
        <label for="{{form.id_for_label}}">{{form.label}}</label>
        {{form}}
    </div>
    {%endfor%}

    {%if error%}
    {{error}}
    {%endif%}
<div style="padding-left: 275px;padding-top: 10px">
<button type = "submit" class="btn text-white" onclick ="location.href='/review/list'" style="background-color:#19bec9;width: 150px;border-radius: 15px;">수정완료</button>
</div>
</form>
    </div>
</div>
</div>

    </body>
    </div>
{% endblock %}

review/templates/review_write.html
{% extends "base.html" %}
{% block content %}
    <head>
<style>
    *{
        font-family: 'NanumBarunGothicLight';

    }
            body {
            background-image:url('/static/img/main.png');
            background-repeat: no-repeat;
            background-size: cover;
            background-color: #f2f2f6;
            }

</style>
        </head>
    <div>
    <body >
<div style="padding-top: 50px;padding-left: 205px">
<div class= "container my-3"  style="background-color:#ffffff; border-radius: 20px;
  width: 1000px;
  height: 700px;
  transform: translate(0%, 5%);
  margin: 5%; /*위 오 아 왼*/
">
<h4 style="padding-top: 20px;text-align: center" >{{place}}에 대한 리뷰를 작성해주세요 !</h4>
<hr>

<div style="padding-top: 25px;padding-left: 140px; clear: left">
<form action="" method = 'POST' >
    {% csrf_token %}
    {%for form in forms%}
    <div >
        <label for="{{form.id_for_label}}">{{form.label}}</label>
        {{form}}
    </div>
    {%endfor%}

    {%if error%}
    {{error}}
    {%endif%}
<div style="padding-left: 275px;padding-top: 10px">
<button type = "submit" class="btn text-white" onclick ="location.href='/review/list'" style="background-color:#19bec9;width: 150px;border-radius: 15px;">작성 완료</button>
</div>
</form>

    </div>
</div>
</div>

    </body>
    </div>
{% endblock %}