TRAIVLER/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import main
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/',include('django_summernote.urls')),
    path('user/', include('user.urls')),
    path('', main),
    path('notice/',include('notice.urls')),
    path('ai/',include('ai.urls')),
    path('review/',include('review.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ai/urls.py
from django.urls import path
from . import views
app_name = 'ai'
urlpatterns = [
   path('result',views.result, name='result'),
   path('info',views.info, name = 'info'),
   path('db_upload',views.db_upload,name = 'db_upload'),
   
]

review/urls.py
from django.urls import path
from . import views
app_name = 'review'
urlpatterns = [
   path('list',views.review_list, name='review_list'),
   path('write',views.review_write,name = "review_write"),
   path('<int:pk>/', views.review_detail, name='review_detail'),
   path('<int:pk>/modify/', views.review_modify, name='review_modify'),
   path('<int:pk>/delete/', views.review_delete, name='review_delete'),
]

ai/models.py
from django.db import models

# Create your models here.
class AiModel(models.Model):
    
    ai_file = models.FileField(blank=True, unique=True) 
    

class Result(models.Model): 
    
    input = models.CharField(max_length = 128,verbose_name = '입력 텍스트',blank = True)
    result = models.TextField(verbose_name = '출력 장소', blank = True) 


class Place(models.Model):
    
    place_name = models.CharField(max_length = 128, unique=True,verbose_name='장소 이름',primary_key=True)
    place_address = models.TextField(verbose_name = '장소 주소',blank=True)
    place_latitude = models.FloatField(verbose_name='위도')
    place_longitude = models.FloatField(verbose_name='경도')
    place_phone = models.TextField(verbose_name='전화번호',blank = True)
    
    def __str__(self):
        return self.place_name

ai/forms.py
from django import forms
from .models import *

class ResultForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = ['input','result']
        
class AiModelForm(forms.ModelForm):
    class Meta:
        model = AiModel
        fields = ['ai_file']
        

ai/views.py
from django.shortcuts import render, redirect

import logging
from django.conf import settings
from django.core.files.storage import default_storage
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import gluonnlp as nlp
import numpy as np
from tqdm import tqdm, tqdm_notebook
#kobert
from kobert.utils import get_tokenizer
from kobert.pytorch_kobert import get_pytorch_kobert_model
import pandas as pd
import pandas as pd
from .models import Place


# from pybo.model import Result
from .models import Result
from .models import AiModel
bertmodel, vocab = get_pytorch_kobert_model()
tokenizer = get_tokenizer()
tok = nlp.data.BERTSPTokenizer(tokenizer, vocab, lower=False)

class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, max_len,
                 pad, pair):
        transform = nlp.data.BERTSentenceTransform(
            bert_tokenizer, max_seq_length=max_len, pad=pad, pair=pair)

        self.sentences = [transform([i[sent_idx]]) for i in dataset]
        self.labels = [np.int32(i[label_idx]) for i in dataset]

    def __getitem__(self, i):
        return (self.sentences[i] + (self.labels[i], ))

    def __len__(self):
        return (len(self.labels))
def predict(predict_sentence):

    data = [predict_sentence, '0']
    dataset_another = [data]

    another_test = BERTDataset(dataset_another, 0, 1, tok, 64, True, False)
    test_dataloader = torch.utils.data.DataLoader(another_test, batch_size=2, num_workers=0)
    model = BERTClassifier(bertmodel,  dr_rate=0.5)
    model_path = AiModel.objects.get(pk=1).ai_file.path
    model.load_state_dict(torch.load(model_path,map_location=torch.device('cpu')))
    model.eval()

    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(test_dataloader):
        token_ids = token_ids.long().to('cpu')
        segment_ids = segment_ids.long().to('cpu')

        valid_length= valid_length
        label = label.long().to('cpu')
        
        out = model(token_ids, valid_length, segment_ids)
    
    return out
class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 num_classes=771,   ##클래스 수 조정##
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate
                 
        self.classifier = nn.Linear(hidden_size , num_classes)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)
    
    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)
        
        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device),return_dict=False)
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

def result(request):
             
    result = Result()
    
    text = request.POST.get('input_text',None)
    result.input = text
    pred = predict(text)
    pred = pred.detach().cpu().numpy()
    top5 =sorted(pred[0], reverse = True)[:5]
    top10 =sorted(pred[0], reverse = True)[:10]
    df = pd.read_csv('label/label_lst_3.csv')
    lst = df['name']
    idx = [] # top5 index 찾기
    for i in top5:
        idx.append(np.where(pred == i)[1][0])

    result_lst = [] # top5 index로 가게 이름 찾기
    for i in idx:
        result_lst.append(lst[i])
    
    result.result = result_lst
    result.save()


    num_lst = [round((2**i)*(i/sum(top5)),2) for i in top5]
    visual_df = pd.DataFrame(columns = ['추천 결과', '추천 수치'])
    visual_df['추천 결과'] = result_lst
    visual_df['추천 수치'] = num_lst

    context = {
        'result': result,
        'result_lst':result_lst,
        'chart_percent' : num_lst
        }
    
    return render(request, 'result.html', context)

def info(request):
    info = request.POST.get('result_info',None) 
    place = Place.  objects.get(place_name = info)
    address = place.place_address
    latitude = place.place_latitude
    longitude = place.place_longitude
    phone = place.place_phone
    context = {
        'info' : info,
        'address': address,
        'latitude': latitude,
        'longitude': longitude,
        'phone' : phone,
    }
    return render(request,'info.html',context)

def db_upload(request):
    df = pd.read_csv("./db_221231_je.csv") 
    
    for i in range(df.shape[0]):
        db =  Place()
        db.place_name = df.iloc[i]['명칭']
        db.place_address = df.iloc[i]['주소']
        db.place_latitude = df.iloc[i]['위도']
        db.place_longitude = df.iloc[i]['경도']
        db.place_phone = df.iloc[i]['문의 및 안내']
        db.save()
    
    return render(request,'db_upload.html')

ai/templates/db_upload.html
<div>db 업로드 완료!!</div>

ai/templates/info.html
{% extends "base.html" %}username
{% block content %}
<head>
<style>
    *{
        font-family: 'NanumBarunGothicLight';

    }
            body {
                background-image:url('/static/img/main.png');
                background-repeat: no-repeat;
                background-size: cover;
                background-color: #f2f2f6;
            }

</style>
        </head>
    <div>
    <body>

    <div style="padding-top: 50px;">

<div class="container my-3" style=" padding:50px;width: 70%;height: 550px;border-radius: 20px; background-color: #ffffff">
<div style="padding-bottom: 5px;width:500px; border-right:1px solid #d3d3d3; padding-right:20px; text-align:justify;height: 400;float: left;margin:0 20px 0 0px">
<h4>{{info}}</h4>
<div style="padding-left:800px;padding-top: 20px">
</div>
<div>

<h6 style="font-size: medium; font-weight: bold;">&emsp;위치:{{address}}</h6>



<div id="map" style="width:300px;height:150px;"></div> <!-- 맵 사이즈 조절 -->
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d1b6fddb09ec0484751e39ef2854cf07"></script> <!--여기에 api 키-->
                        <script>
                            
                            let latitude = {{latitude}}
                            let longitude = {{longitude}}
                            var placename = "{{info}}"
                            var container = document.getElementById('map'); // 지도를 넣을 div 지정
                            var options = {
                                center: new kakao.maps.LatLng(latitude, longitude), // 여기에 위도, 경도 집어넣으면 지도가 해당 좌표를 중앙으로 나옴(현 좌표는 밀락더마켓)
                                // center : new kakao.maps.LatLng(db 위도, db 경도)
                                level: 3 // 레벨을 통해서 지도 크기 지정 가능
                            };

                            var map = new kakao.maps.Map(container, options); // 지도 생성

                            // 마커로 사용할 이미지 삽입
                            var imageSrc = "http://t1.daumcdn.net/localimg/localimages/07/2018/pc/img/marker_spot.png"; // 이건 카카오맵 공식 마커 이미지
                            // 마커 이미지 크기
                            var imageSize = new kakao.maps.Size(24, 35);
                            // 마커 이미지 생성
                            var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);
                            // 마커 생성
                            var marker = new kakao.maps.Marker({
                                map : map, // 마커가 들어갈 지도
                                position : new kakao.maps.LatLng(latitude, longitude), // 맵 중심 좌표와 동일하게 하면 될 듯
                                title : placename, // 마커 위에 마우스 갖다대면 보일 텍스트
                                image : markerImage, // 표시할 마커 이미지
                            })

                        </script>



                     
    <div>
        문의 및 연락처 : {{phone}}
        <div style="padding-top: 30px">    
            <ul>
            <h6 style="float: left;">아직 등록된 리뷰가 없습니다.&emsp;</h6>
            <h6 style="float: left; padding-left: 5px">익명&emsp;</h6>
            <h6 style="padding-left: 5px">2022-12-29</h6>
            </ul>
            <ul style="padding-top: 10px">
            <h6 style="float: left;">아직 등록된 리뷰가 없습니다.&emsp;</h6>
            <h6 style="float: left; padding-left: 5px">익명&emsp;</h6>
            <h6 style="padding-left: 5px">2022-12-29</h6>
            </ul>
            <ul style="padding-top: 10px">
            <h6 style="float: left;">아직 등록된 리뷰가 없습니다.&emsp;</h6>
            <h6 style="float: left; padding-left: 5px">익명&emsp;</h6>
            <h6 style="padding-left: 5px">2022-12-29</h6>
            </ul>
            <ul style="padding-top: 10px">
            <h6 style="float: left;">아직 등록된 리뷰가 없습니다.&emsp;</h6>
            <h6 style="float: left; padding-left: 5px">익명&emsp;</h6>
            <h6 style="padding-left: 5px">2022-12-29</h6>
            </ul>
            <ul style="padding-top: 10px">
            <h6 style="float: left;">아직 등록된 리뷰가 없습니다.&emsp;</h6>
            <h6 style="float: left; padding-left: 5px">익명&emsp;</h6>
            <h6 style="padding-left: 5px">2022-12-29</h6>
            </ul>
    </div>   
</div>
</div>
</div>
<div >
    <h6 style="padding-top:30px;padding-left:50px"></h6>
    <img src="/static/label_img/{{info}}.jpg" alt="" style="line-height: 80%;width:450px;height:300px">
    </div>
    <div style="padding-top: 30px; padding-left: 650px;clear:left">
        
        
            <form method="GET" action = "{% url 'review:review_write' %}">{% csrf_token %}
                <button type = 'submit' name = 'place_info' class="button3" id="review_btn" value = {{info}} style="background-color:#19bec9;width: 150px;border-radius: 15px">리뷰작성</input>
            </form>
            <button type = 'button' class="button3" id="detail_btn" onclick=history.back() style="background-color:#19bec9;width: 150px;border-radius: 15px;">닫기</button>

            <style>
             .button3 {
             /*세로 가로*/
            border: none;
            color:white;
            background-color: #19bec9;
            cursor: pointer;
            width: 50%;
            height: 35px;
            font-weight: bold;
            text-rendering: auto;
            letter-spacing: normal;
            word-spacing: normal;
            text-transform: none;
            text-indent: 0px;
            text-shadow: none;
            font-size: 17px;
            border-radius: 15px;
            float : left;

          }
            </style>
        
    
    
</div>
</div>

    </div>
    </body>
    </div>
{% endblock %}

ai/templates/register_wishlist.html
{%load static%}
{%block contents%}
<div>언제 방문하고 싶나요? </div>
<form action="" method = 'POST'>
    {% csrf_token %}
    {%for form in forms%}
    <div>
        <label for="{{form.id_for_label}}">{{form.label}}</label>
        {{form}}
    </div>
    {%endfor%}

    {%if error%}
    {{error}}
    {%endif%}
    <p><input type="date" value="2022-12-25"></p>
    <p><input type="submit" value="Submit"></p>
</form>

{% endblock contents%}